name: Monitor Dependencies

on:
  push:
    branches:
      - master

jobs:
  extract-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Extract dependencies
        run: |
          cargo metadata --format-version=1 > dependencies.json
      - name: Upload dependency info
        uses: actions/upload-artifact@v2
        with:
          name: dependencies
          path: dependencies.json